{% set name = "psycopg" %}
{% set version = "3.1.13" %}
{% set build_number = 0 %}

package:
  name: psycopg-split
  version: {{ version }}

source:
  - folder: psycopg
    url: https://pypi.io/packages/source/p/psycopg/psycopg-{{ version }}.tar.gz
    sha256: e6d047ce16950651d6e26c7c19ca57cc42e1d4841b58729f691244baeee46e30
    patches:
      - 0001-remove-tzdata-for-pip-check.patch

  - folder: psycopg-c
    url: https://pypi.io/packages/source/p/psycopg-c/psycopg-c-{{ version }}.tar.gz
    sha256: a7f39d29e5ba46cdc5ff6b40a1e418dba034efd2faf7369a8b6d20effbd2a19d

build:
  number: {{ build_number }}

requirements:
  host:
    - python
  run:
    - python

outputs:

  - name: psycopg-c
    script: install_psycopg-c.sh  # [linux and py<=38]
    build:
      number: {{ build_number }}
      script: cd psycopg-c && {{ PYTHON }} -m pip install . -vv  # [not linux or py>38]

    requirements:
      build:
        - {{ compiler('c') }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - postgresql                             # [build_platform != target_platform]
      host:
        - python
        - pip
        - postgresql
      run:
        # libpq is a repackaging of only the library to connect to postgres
        - libpq
        - python
    test:
      commands:
        - pip check
      requires:
        - pip

  - name: psycopg
    build:
      number: {{ build_number }}
      script: cd psycopg && {{ PYTHON }} -m pip install . -vv --no-deps

    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - postgresql                             # [build_platform != target_platform]
      host:
        - python
        - pip
        - backports.zoneinfo  # [py<39]
        - postgresql
        - typing-extensions  # [py<38]
        - tzdata  # [win]
      run:
        - python
        - {{ pin_subpackage('psycopg-c', max_pin='x.x.x.x.x.x') }}
        - backports.zoneinfo >=0.2.0  # [py<39]
        # libpq is a repackaging of only the library to connect to postgres
        - libpq
        - typing-extensions >=4.1
        - tzdata  # [win]

    test:
      imports:
        - psycopg
        - psycopg.pq
        - psycopg_c
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://psycopg.org/psycopg3/
  summary: PostgreSQL database adapter for Python
  description: |
    Psycopg 3 is a newly designed PostgreSQL database adapter for the Python
    programming language. Psycopg 3 presents a familiar interface for everyone
    who has used Psycopg 2 or any other DB-API 2.0 database adapter, but allows
    to use more modern PostgreSQL and Python features.
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  doc_url: https://www.psycopg.org/psycopg3/docs/
  dev_url: https://github.com/psycopg/psycopg/

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - xylar
